require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReceitamedicasController do

  # This should return the minimal set of attributes required to create a valid
  # Receitamedica. As you add validations to Receitamedica, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nomeMedicamento" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReceitamedicasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all receitamedicas as @receitamedicas" do
      receitamedica = Receitamedica.create! valid_attributes
      get :index, {}, valid_session
      assigns(:receitamedicas).should eq([receitamedica])
    end
  end

  describe "GET show" do
    it "assigns the requested receitamedica as @receitamedica" do
      receitamedica = Receitamedica.create! valid_attributes
      get :show, {:id => receitamedica.to_param}, valid_session
      assigns(:receitamedica).should eq(receitamedica)
    end
  end

  describe "GET new" do
    it "assigns a new receitamedica as @receitamedica" do
      get :new, {}, valid_session
      assigns(:receitamedica).should be_a_new(Receitamedica)
    end
  end

  describe "GET edit" do
    it "assigns the requested receitamedica as @receitamedica" do
      receitamedica = Receitamedica.create! valid_attributes
      get :edit, {:id => receitamedica.to_param}, valid_session
      assigns(:receitamedica).should eq(receitamedica)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Receitamedica" do
        expect {
          post :create, {:receitamedica => valid_attributes}, valid_session
        }.to change(Receitamedica, :count).by(1)
      end

      it "assigns a newly created receitamedica as @receitamedica" do
        post :create, {:receitamedica => valid_attributes}, valid_session
        assigns(:receitamedica).should be_a(Receitamedica)
        assigns(:receitamedica).should be_persisted
      end

      it "redirects to the created receitamedica" do
        post :create, {:receitamedica => valid_attributes}, valid_session
        response.should redirect_to(Receitamedica.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved receitamedica as @receitamedica" do
        # Trigger the behavior that occurs when invalid params are submitted
        Receitamedica.any_instance.stub(:save).and_return(false)
        post :create, {:receitamedica => { "nomeMedicamento" => "invalid value" }}, valid_session
        assigns(:receitamedica).should be_a_new(Receitamedica)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Receitamedica.any_instance.stub(:save).and_return(false)
        post :create, {:receitamedica => { "nomeMedicamento" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested receitamedica" do
        receitamedica = Receitamedica.create! valid_attributes
        # Assuming there are no other receitamedicas in the database, this
        # specifies that the Receitamedica created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Receitamedica.any_instance.should_receive(:update_attributes).with({ "nomeMedicamento" => "MyString" })
        put :update, {:id => receitamedica.to_param, :receitamedica => { "nomeMedicamento" => "MyString" }}, valid_session
      end

      it "assigns the requested receitamedica as @receitamedica" do
        receitamedica = Receitamedica.create! valid_attributes
        put :update, {:id => receitamedica.to_param, :receitamedica => valid_attributes}, valid_session
        assigns(:receitamedica).should eq(receitamedica)
      end

      it "redirects to the receitamedica" do
        receitamedica = Receitamedica.create! valid_attributes
        put :update, {:id => receitamedica.to_param, :receitamedica => valid_attributes}, valid_session
        response.should redirect_to(receitamedica)
      end
    end

    describe "with invalid params" do
      it "assigns the receitamedica as @receitamedica" do
        receitamedica = Receitamedica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Receitamedica.any_instance.stub(:save).and_return(false)
        put :update, {:id => receitamedica.to_param, :receitamedica => { "nomeMedicamento" => "invalid value" }}, valid_session
        assigns(:receitamedica).should eq(receitamedica)
      end

      it "re-renders the 'edit' template" do
        receitamedica = Receitamedica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Receitamedica.any_instance.stub(:save).and_return(false)
        put :update, {:id => receitamedica.to_param, :receitamedica => { "nomeMedicamento" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested receitamedica" do
      receitamedica = Receitamedica.create! valid_attributes
      expect {
        delete :destroy, {:id => receitamedica.to_param}, valid_session
      }.to change(Receitamedica, :count).by(-1)
    end

    it "redirects to the receitamedicas list" do
      receitamedica = Receitamedica.create! valid_attributes
      delete :destroy, {:id => receitamedica.to_param}, valid_session
      response.should redirect_to(receitamedicas_url)
    end
  end

end
